#### General information about the project    ####
#### All this will be visible on DataCamp.com ####
title          : "Exploring the National Immunization Survey."
description    : >
  Exploratory data analysis and basic Python data wrangling, using the US 2016 National Immunization Survey.
long_description: |
  Practice basic data wrangling with Python and pandas and exploratory data analysis with pyplot,
  while exploring data from the US Center for Disease Control's 2016 National Immunization Survey.
  This project builds on skills and terms introduced in [Intro to Python for Data Science](https://www.datacamp.com/courses/intro-to-python-for-data-science) and
  [Intermediate Python for Data Science](https://www.datacamp.com/courses/intermediate-python-for-data-science).
time_needed: "60 minutes" # "30/45/60 minutes".
instructors: # DataCamp connected email of the creator of the Project
  - kshaffer@umw.edu
collaborators: # DataCamp connected email of people that helped with the Project
  - kshaffer@umw.edu

#### Metadata regarding course requirements and topics ####
#### This will be updated by your DataCamp contact     ####
technology: 2 # 1 == R, 2 == python, 3 == sql
# IDs for courses that are prerequisites
# See https://mb.datacamp.com/question/126 for IDs
prerequisites:
  - 799
difficulty_level: 1 # 1 == easy, 2 == medium, 3 == hard
# IDs for the topics the project covers
# See https://authoring.datacamp.com/projects/projects-repo-structure.html#project-yml for IDs
topics:
  - 3
  - 4
  - 8

#### Technical settings for the docker image running the project ####
#### This will be updated by your DataCamp contact.              ####
language       : python # One of r, python or sql
# The name of the docker image used to run the course
from           : 'python-notebooks-prod:109'
runtime_config : default # default/heavy . Set to heavy for more resource intensive projects.
